Containerized Extension
vre-hub/zenodo-jupyterlab-extension pull request #47
Opened 2024-07-24 13:41 UTC by mrzengel

Closes #40

2024-07-24 15:42 UTC, garciagenrique commented on Dockerfile
> +RUN git clone https://github.com/vre-hub/zenodo-jupyterlab-extension.git
This would just clone the state of main, not of the desired branch, in case we would like to build the image from another branch.
Any suggestion on how to solve this ?

2024-07-24 16:01 UTC, mrzengel commented on Dockerfile
> +RUN git clone https://github.com/vre-hub/zenodo-jupyterlab-extension.git
I think if we do:
`git clone ${{ github.head_ref }} --single-branch https://github.com/vre-hub/zenodo-jupyterlab-extension.git`
this should what you're saying and dynamically pull the branch name from where the PR originated

2024-07-24 16:11 UTC, mrzengel commented on Dockerfile
> +RUN git clone https://github.com/vre-hub/zenodo-jupyterlab-extension.git
Okay implemented now and it seems to work

2024-07-25 07:42 UTC, Soap2G approved these changes
👍

2024-07-25 09:53 UTC, garciagenrique requested changes

2024-07-25 09:53 UTC, garciagenrique commented on Dockerfile
> +FROM ubuntu:20.04
We are building jupyter extension, thus I suggest to use BASE images that have the basic software installed.
Have a look to https://github.com/jupyter/docker-stacks as well as the dockerhub and/or the quay.io repository

2024-07-25 09:53 UTC, garciagenrique commented on Dockerfile
> +WORKDIR /app
No need to put everything within an extra subdirectory. Working at $HOME is more than enough

2024-07-25 09:53 UTC, garciagenrique commented on Dockerfile
> +RUN git clone --branch ${BRANCH_NAME} --single-branch https://github.com/vre-hub/zenodo-jupyterlab-extension.git
This solution works very well, indeed. However, it isn't a good practice to make calls to git.
What about doing something like (for example)

```docker
COPY . /zenodo_jupyterlab_extension
WORKDIR /zenodo_jupyterlab_extension
```
This would also solve the cases in where we are working from any branch, as the corresponding checkout stage will fetch the correct branch/status

2024-07-25 09:53 UTC, garciagenrique commented on README.md
> +docker run -d -p 8888:8888 ghcr.io/vre-hub/zenodo-jupyterlab-extension`
How can users check for the different versions available ? 
You can either link the github package website, either explain how to browse the different versions of the package.

Also, does `docker run ... <image>` need a tag at the end of the command, or it works without specifying nothing ?

2024-07-25 15:45 UTC, Soap2G commented on Dockerfile
> +FROM ubuntu:20.04
`FROM jupyter/datascience-notebook` is ok, but leaving it without tag means assigning `latest` by default, which we don't want. Let's choose a tag that fixes the version of the base notebook.

2024-07-25 15:45 UTC, Soap2G commented on README.md
> +docker run -d -p 8888:8888 ghcr.io/vre-hub/zenodo-jupyterlab-extension<version>`
A couple of suggestions:
1. "# Docker" with a space in between.
2. I'd directly quote the `run` command, since pulling is automatically included if the image is not found locally; so change 
> To do this, use the following commands: `docker pull ghcr.io/vre-hub/zenodo-jupyterlab-extension:<version>\  docker run -d -p 8888:8888 ghcr.io/vre-hub/zenodo-jupyterlab-extension<version>` 

into 
> To do this, use the following command: `docker run -d -p 8888:8888 ghcr.io/vre-hub/zenodo-jupyterlab-extension<version>`

2024-07-26 08:25 UTC, garciagenrique requested changes

2024-07-26 08:25 UTC, garciagenrique commented on Dockerfile
> +FROM jupyter/datascience-notebook
Same comment as the one Giovanni did here. If we don't specify a version, we will just pull `latest` and we will lost track of any kind of software stack versioning.
Also, the data science notebook is quite heavy. I will suggest to go with `scipy-notebook` and a tag that brings a specific python version, let's say `python-3.11.9`.

Btw, jupyter project has stopped using dockerhub and moved to quay.io (don't know of the exact reasons), so we will need to start pulling from there :)

ref: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html

2024-07-26 09:02 UTC, mrzengel commented
Okay I think I've incorporated everything y'all have commented

2024-07-26 13:30 UTC, garciagenrique approved these changes

2024-07-26 13:34 UTC, merged